#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use Getopt::Long;
use File::Basename;

# Default values
my $indicator = $ENV{BLOCK_INSTANCE} || "CAPS";
my $color_on  = "#00FF00";
my $color_off = "#222222";

sub help {
    my $program = basename($0);
    printf "Usage: %s [-c <color on>] [-C <color off>]\n", $program;
    printf "  -c <color on>: hex color to use when indicator is on\n";
    printf "  -C <color off>: hex color to use when indicator is off\n";
    printf "\n";
    printf "Note: environment variable \$BLOCK_INSTANCE should be one of:\n";
    printf "  CAPS, NUM (default is CAPS).\n";
    exit 0;
}

Getopt::Long::config qw(no_ignore_case);
GetOptions("help|h" => \&help,
           "c=s"    => \$color_on,
           "C=s"    => \$color_off) or exit 1;

# Key mapping
my %indicators = (
    CAPS => 0x00000001,
    NUM  => 0x00000002,
);

# Retrieve key flags
my $mask = 0;
open(XSET, "xset -q |") or die;
while (<XSET>) {
    if (/LED mask:\s*([0-9]+)/) {
        $mask = $1;
        last;
    }
}
close(XSET);

# Output
printf "%s\n", $indicator;
printf "%s\n", $indicator;
if (($indicators{$indicator} || 0) & $mask) {
    printf "%s\n", $color_on;
} else {
    printf "%s\n", $color_off;
}
exit 0
